# Generated by Django 3.1.14 on 2022-02-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsCloud', '0003_wordscloud_all_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordscloud',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5),
        ),
    ]
