# Generated by Django 3.1.8 on 2021-12-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20211129_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientitem',
            name='nom_entreprise',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Entreprise'),
        ),
    ]
