# Generated by Django 3.1.8 on 2021-11-29 13:09

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipe',
            old_name='description_projet',
            new_name='description_principale',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='annee_projet',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='content',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='nom_projet',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='thumbnail_projet',
        ),
        migrations.AddField(
            model_name='equipe',
            name='team_user',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Photo'))]))], blank=True, null=True),
        ),
    ]
