# Generated by Django 3.1.8 on 2021-12-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentuser',
            name='email_link',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
