# Generated by Django 3.1.8 on 2021-11-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0002_auto_20211129_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentuser',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
