# Generated by Django 3.1.8 on 2021-12-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0002_auto_20211222_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentuser',
            name='email_link',
            field=models.CharField(blank=True, default='###@gmail.com', max_length=100, null=True),
        ),
    ]
