# Generated by Django 3.1.8 on 2021-12-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0003_auto_20211129_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentuser',
            name='description_user',
        ),
        migrations.AddField(
            model_name='contentuser',
            name='role_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
