# Generated by Django 3.1.8 on 2021-11-29 13:37

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('equipe', '0003_auto_20211129_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='nom_user',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='team_user',
        ),
        migrations.CreateModel(
            name='ContentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('nom_user', models.CharField(blank=True, max_length=100, null=True)),
                ('description_user', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('external_link', models.CharField(blank=True, max_length=100, null=True)),
                ('image_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_user', to='equipe.equipe')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
