# Generated by Django 3.1.8 on 2022-01-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='video_header',
        ),
    ]
