# Generated by Django 3.1.8 on 2022-01-03 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0004_duration_optional_floatfield'),
        ('home', '0002_remove_homepage_video_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='video_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media'),
        ),
    ]
