# Generated by Django 3.1.8 on 2022-01-03 19:00

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0004_duration_optional_floatfield'),
        ('home', '0003_homepage_video_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='img_header',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='title_footer',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='title_projets',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='title_team',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='title_wordsCloud',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='video_header',
        ),
        migrations.CreateModel(
            name='videoHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_header', to='home.homepage')),
                ('video_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
