# Generated by Django 3.1.8 on 2022-01-09 17:05

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220103_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='title_header',
            new_name='header_tagline',
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_tagline',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
