# Generated by Django 3.1.8 on 2021-11-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211129_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='bodyHeader',
            new_name='title_bodyHeader',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='contact',
            new_name='title_contact',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='footer',
            new_name='title_footer',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='projets',
            new_name='title_projets',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='team',
            new_name='title_team',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='wordsCloud',
            new_name='title_wordsCloud',
        ),
    ]
