# Generated by Django 3.1.8 on 2021-11-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211129_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='projets',
        ),
    ]
