# Generated by Django 3.1.8 on 2022-01-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220109_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='header_tagline',
        ),
        migrations.AddField(
            model_name='homepage',
            name='line_1_tagline',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='line_2_tagline',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title_tagline',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
