# Generated by Django 3.1.8 on 2021-11-29 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0005_auto_20211129_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='title_bodyHeader',
            new_name='title_header',
        ),
        migrations.AddField(
            model_name='homepage',
            name='img_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
