# Generated by Django 3.1.8 on 2021-11-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_projets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='equipe',
            new_name='team',
        ),
    ]
