# Generated by Django 3.1.8 on 2021-11-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0008_equipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipe',
        ),
    ]
