# Generated by Django 3.1.8 on 2021-11-29 16:20

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetslist',
            name='projetTxt',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=100, null=True),
        ),
    ]
