# Generated by Django 3.1.8 on 2022-01-09 16:54

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_footer_logo_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='info_contact_second',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
