# Generated by Django 3.1.14 on 2022-02-24 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('footer', '0003_footer_info_contact_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='img_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
